include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
    - '**/generated_plugin_registrant.dart'

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    cascade_invocations: false
