name: very_good_coffee
description: Very Good Coffee app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: 3.24.3

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  json_serializable: ^6.8.0
  mocktail_image_network: ^1.2.0
  riverpod_annotation: ^2.3.5
  transparent_image: ^2.0.1

dev_dependencies:
  bdd_widget_test: ^1.7.4
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
